# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/marcelo/Documentos/Tager-Assembler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/marcelo/Documentos/Tager-Assembler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marcelo/Documentos/Tager-Assembler/CMakeFiles /home/marcelo/Documentos/Tager-Assembler//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marcelo/Documentos/Tager-Assembler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tager

# Build rule for target.
tager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tager
.PHONY : tager

# fast build rule for target.
tager/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tager.dir/build.make CMakeFiles/tager.dir/build
.PHONY : tager/fast

src/files.o: src/files.c.o
.PHONY : src/files.o

# target to build an object file
src/files.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tager.dir/build.make CMakeFiles/tager.dir/src/files.c.o
.PHONY : src/files.c.o

src/files.i: src/files.c.i
.PHONY : src/files.i

# target to preprocess a source file
src/files.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tager.dir/build.make CMakeFiles/tager.dir/src/files.c.i
.PHONY : src/files.c.i

src/files.s: src/files.c.s
.PHONY : src/files.s

# target to generate assembly for a file
src/files.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tager.dir/build.make CMakeFiles/tager.dir/src/files.c.s
.PHONY : src/files.c.s

src/linked_list.o: src/linked_list.c.o
.PHONY : src/linked_list.o

# target to build an object file
src/linked_list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tager.dir/build.make CMakeFiles/tager.dir/src/linked_list.c.o
.PHONY : src/linked_list.c.o

src/linked_list.i: src/linked_list.c.i
.PHONY : src/linked_list.i

# target to preprocess a source file
src/linked_list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tager.dir/build.make CMakeFiles/tager.dir/src/linked_list.c.i
.PHONY : src/linked_list.c.i

src/linked_list.s: src/linked_list.c.s
.PHONY : src/linked_list.s

# target to generate assembly for a file
src/linked_list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tager.dir/build.make CMakeFiles/tager.dir/src/linked_list.c.s
.PHONY : src/linked_list.c.s

src/strings.o: src/strings.c.o
.PHONY : src/strings.o

# target to build an object file
src/strings.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tager.dir/build.make CMakeFiles/tager.dir/src/strings.c.o
.PHONY : src/strings.c.o

src/strings.i: src/strings.c.i
.PHONY : src/strings.i

# target to preprocess a source file
src/strings.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tager.dir/build.make CMakeFiles/tager.dir/src/strings.c.i
.PHONY : src/strings.c.i

src/strings.s: src/strings.c.s
.PHONY : src/strings.s

# target to generate assembly for a file
src/strings.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tager.dir/build.make CMakeFiles/tager.dir/src/strings.c.s
.PHONY : src/strings.c.s

src/tager.o: src/tager.c.o
.PHONY : src/tager.o

# target to build an object file
src/tager.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tager.dir/build.make CMakeFiles/tager.dir/src/tager.c.o
.PHONY : src/tager.c.o

src/tager.i: src/tager.c.i
.PHONY : src/tager.i

# target to preprocess a source file
src/tager.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tager.dir/build.make CMakeFiles/tager.dir/src/tager.c.i
.PHONY : src/tager.c.i

src/tager.s: src/tager.c.s
.PHONY : src/tager.s

# target to generate assembly for a file
src/tager.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tager.dir/build.make CMakeFiles/tager.dir/src/tager.c.s
.PHONY : src/tager.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tager"
	@echo "... src/files.o"
	@echo "... src/files.i"
	@echo "... src/files.s"
	@echo "... src/linked_list.o"
	@echo "... src/linked_list.i"
	@echo "... src/linked_list.s"
	@echo "... src/strings.o"
	@echo "... src/strings.i"
	@echo "... src/strings.s"
	@echo "... src/tager.o"
	@echo "... src/tager.i"
	@echo "... src/tager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

